// esteidpluginie.idl : IDL source for esteid-plugin-ie
//

// This file will be processed by the MIDL tool to
// produce the type library (esteidpluginie.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(A0024F85-5662-40C3-B0A9-85646EA788ED),
	dual,
	nonextensible,
	helpstring("IEstEIDIEPluginBHO Interface"),
	pointer_default(unique)
]
interface IEstEIDIEPluginBHO : IDispatch{
	[propget, id(1), helpstring("property version")] HRESULT version([out, retval] BSTR *result);
	[propget, id(2), helpstring("property errorMessage")] HRESULT errorMessage([out, retval] BSTR *result);
	[propget, id(3), helpstring("property errorCode")] HRESULT errorCode([out, retval] BSTR *result);
	[propget, id(4), helpstring("property language")] HRESULT pluginLanguage([out, retval] BSTR *result);
	[propput, id(4), helpstring("property language")] HRESULT pluginLanguage([in] BSTR language);
	[id(6), helpstring("method getCertificate()")] HRESULT getCertificate([in, optional] VARIANT filter, [out, retval] IDispatch **certificate);
	[id(7), helpstring("method sign()")] HRESULT sign([in] BSTR id, [in] BSTR hash, [in] BSTR language, [in, optional] VARIANT info, [out, retval] BSTR *signature); 
};
[
	object,
	uuid(3ECA2169-2EFC-4EB5-B83A-8DC2A6688904),
	dual,
	nonextensible,
	helpstring("IEstEIDCertificate Interface"),
	pointer_default(unique)
]
interface IEstEIDCertificate : IDispatch{
	[propget, id(1), helpstring("property certificate id")] HRESULT id([out, retval] BSTR *id);
	[propget, id(2), helpstring("property certificate certificateAsHex")] HRESULT certificateAsHex([out, retval] BSTR *certificate);
	[propget, id(3), helpstring("property certificate cert (certificateAsHex)")] HRESULT cert([out, retval] BSTR *certificate);
	[id(4), helpstring("method Init")] HRESULT Init([in, optional] VARIANT filter);
};
[
	uuid(76BC53BB-3D87-4755-B85F-48C7395A6578),
	version(1.0),
	helpstring("esteidpluginie 1.0 Type Library")
]
library esteidpluginieLib
{
	importlib("stdole2.tlb");
	[
		uuid(880A49C2-E366-45A9-902B-2FBFA537FB8F),
		helpstring("EstEIDIEPluginBHO Class")
	]
	coclass EstEIDIEPluginBHO
	{
		[default] interface IEstEIDIEPluginBHO;
	};
	[
		uuid(9BF5CDBC-D173-44DF-9A41-7D654D478A11),
		helpstring("EstEIDCertificate Class")
	]
	coclass EstEIDCertificate
	{
		[default] interface IEstEIDCertificate;
	};
};
